version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit-hooks:
        patterns:
          - "*"
