# https://github.com/DavidAnson/markdownlint#rules--aliases

# MD013/line-length Line length
MD013: false

# MD024/no-duplicate-heading No duplicate headings
MD024: false

# MD051/link-fragments Link fragments
MD051: false

# MD033/no-inline-html Inline HTML
MD033:
  allowed_elements: ["div", "h1"]

# MD036/no-emphasis-as-heading Emphasis used instead of a heading
MD036: false

# MD041/first-line-heading/first-line-h1
MD041: false

# MD042/no-empty-links No empty links
MD042: false

# MD060/table-column-style Table column style
MD060: false
