// _data/levels.js
module.exports = [
  // 0-10: Original Ranks
  { level: 0, name: "Newbie", emoji: "🐣", color: "#94a3b8" },
  { level: 1, name: "Script Kid", emoji: "🛹", color: "#10b981" },
  { level: 2, name: "Code Breaker", emoji: "🕵️‍♂️", color: "#f59e0b" },
  { level: 3, name: "Void Walker", emoji: "🌌", color: "#6366f1" },
  { level: 4, name: "Bug Hunter", emoji: "🐛", color: "#84cc16" },
  { level: 5, name: "Data Miner", emoji: "💎", color: "#06b6d4" },
  { level: 6, name: "Sys Admin", emoji: "🛠️", color: "#ec4899" },
  { level: 7, name: "Terminal Pro", emoji: "⌨️", color: "#7c3aed" },
  { level: 8, name: "Cloud Expert", emoji: "☁️", color: "#3b82f6" },
  { level: 9, name: "Full Stack", emoji: "🥞", color: "#f97316" },
  { level: 10, name: "Architect", emoji: "👑", color: "#ef4444" },

  // 11-30: Magic the Gathering (Creatures & Keywords)
  { level: 11, name: "Llanowar Elf", emoji: "🏹", color: "#2d5a27" },
  { level: 12, name: "Scryer", emoji: "🔮", color: "#1d4ed8" },
  { level: 13, name: "Trampler", emoji: "🐘", color: "#15803d" },
  { level: 14, name: "Flying Menace", emoji: "🦇", color: "#4a044e" },
  { level: 15, name: "Mana Leech", emoji: "💧", color: "#0ea5e9" },
  { level: 16, name: "Spellcounter", emoji: "🚫", color: "#2563eb" },
  { level: 17, name: "Goblin Guide", emoji: "👺", color: "#dc2626" },
  { level: 18, name: "Serum Visionary", emoji: "🧪", color: "#6366f1" },
  { level: 19, name: "Mythic Rare", emoji: "🟠", color: "#f97316" },
  { level: 20, name: "Planeswalker", emoji: "✨", color: "#fbbf24" },

  // 21-40: Game of Thrones (Houses & Heroes)
  { level: 21, name: "Night's Watch", emoji: "🦅", color: "#1e293b" },
  { level: 22, name: "Wildling Scout", emoji: "❄️", color: "#94a3b8" },
  { level: 23, name: "Ironborn", emoji: "⚓", color: "#475569" },
  { level: 24, name: "Dothraki Rider", emoji: "🐎", color: "#b45309" },
  { level: 25, name: "Kingslayer", emoji: "🗡️", color: "#facc15" },
  { level: 26, name: "Winterfell Warden", emoji: "🐺", color: "#cbd5e1" },
  { level: 27, name: "Dragonstone Guard", emoji: "🐉", color: "#991b1b" },
  { level: 28, name: "Faceless Man", emoji: "🎭", color: "#4b5563" },
  { level: 29, name: "Hand of the King", emoji: "🖐️", color: "#d97706" },
  { level: 30, name: "Iron Throne Heir", emoji: "⚔️", color: "#111827" },

  // 31-50: Wheel of Time (The Tiers of Power)
  { level: 31, name: "Two Rivers Archer", emoji: "🏹", color: "#166534" },
  { level: 32, name: "Gleeman", emoji: "🎶", color: "#be185d" },
  { level: 33, name: "Borderlander", emoji: "🛡️", color: "#991b1b" },
  { level: 34, name: "Warders Bond", emoji: "🔗", color: "#1e293b" },
  { level: 35, name: "Aes Sedai Novice", emoji: "🕯️", color: "#f8fafc" },
  { level: 36, name: "Accepted", emoji: "💍", color: "#e2e8f0" },
  { level: 37, name: "Aiel Dreamwalker", emoji: "🏜️", color: "#d97706" },
  { level: 38, name: "Asha'man", emoji: "⚡", color: "#000000" },
  { level: 39, name: "Amyrlin Seat", emoji: "📜", color: "#ffffff" },
  { level: 40, name: "Ta'veren", emoji: "🌀", color: "#6366f1" },

  // 41-60: Lord of the Rings (Fellowship & Foes)
  { level: 41, name: "Hobbit Adventurer", emoji: "🍺", color: "#15803d" },
  { level: 42, name: "Bree Strider", emoji: "👢", color: "#451a03" },
  { level: 43, name: "Riddermark Lord", emoji: "🏇", color: "#166534" },
  { level: 44, name: "Gondor Soldier", emoji: "🛡️", color: "#94a3b8" },
  { level: 45, name: "Uruk-hai Berserker", emoji: "✋", color: "#450a0a" },
  { level: 46, name: "Elven Archer", emoji: "🍃", color: "#4ade80" },
  { level: 47, name: "Dwarf Warrior", emoji: "⛏️", color: "#78350f" },
  { level: 48, name: "Nazgûl Rider", emoji: "🐎", color: "#020617" },
  { level: 49, name: "Istari Pupil", emoji: "🧙", color: "#3b82f6" },
  { level: 50, name: "Ring-bearer", emoji: "💍", color: "#fbbf24" },

  // NEW LEVELS 51-60
  { level: 51, name: "White Wizard", emoji: "🧙‍♂️", color: "#f8fafc" },
  { level: 52, name: "Silmaril Seeker", emoji: "💎", color: "#7dd3fc" },
  { level: 53, name: "Dune Walker", emoji: "⏳", color: "#fcd34d" },
  { level: 54, name: "Shadowfax Rider", emoji: "🐎", color: "#e2e8f0" },
  { level: 55, name: "Master of Coin", emoji: "🪙", color: "#fbbf24" },
  { level: 56, name: "Kingsguard", emoji: "🛡️", color: "#94a3b8" },
  { level: 57, name: "Valyrian Smith", emoji: "⚒️", color: "#475569" },
  { level: 58, name: "Night Watcher", emoji: "🦉", color: "#312e81" },
  { level: 59, name: "Obsidian Blade", emoji: "🗡️", color: "#1e293b" },
  { level: 60, name: "Citadel Maester", emoji: "📜", color: "#8b5e3c" },

  // 61-80: High Magic & Artifacts
  { level: 61, name: "Mox Emerald", emoji: "💚", color: "#10b981" },
  { level: 62, name: "Mox Sapphire", emoji: "💙", color: "#3b82f6" },
  { level: 63, name: "Mox Ruby", emoji: "❤️", color: "#ef4444" },
  { level: 64, name: "Mox Jet", emoji: "🖤", color: "#18181b" },
  { level: 65, name: "Mox Pearl", emoji: "🤍", color: "#f8fafc" },
  { level: 66, name: "Black Lotus", emoji: "🌺", color: "#000000" },
  { level: 67, name: "Balrog Slayer", emoji: "🔥", color: "#f97316" },
  { level: 68, name: "Witch-king", emoji: "👑", color: "#334155" },
  { level: 69, name: "Shelob's Kin", emoji: "🕷️", color: "#0f172a" },
  { level: 70, name: "Dragon-friend", emoji: "🐲", color: "#dc2626" },

  // NEW LEVELS 71-80
  { level: 71, name: "Neon Ghost", emoji: "👻", color: "#22d3ee" },
  { level: 72, name: "Dragon's Greed", emoji: "🪙", color: "#fbbf24" },
  { level: 73, name: "Mistborn", emoji: "🌫️", color: "#94a3b8" },
  { level: 74, name: "Cinder Soul", emoji: "🔥", color: "#f87171" },
  { level: 75, name: "High Council", emoji: "🏛️", color: "#6366f1" },
  { level: 76, name: "Valyrian Steel", emoji: "🗡️", color: "#cbd5e1" },
  { level: 77, name: "Golden Snitch", emoji: "✨", color: "#facc15" },
  { level: 78, name: "Ether Weaver", emoji: "🕸️", color: "#a855f7" },
  { level: 79, name: "Star Forge", emoji: "🔨", color: "#38bdf8" },
  { level: 80, name: "Mithril Guard", emoji: "🛡️", color: "#e2e8f0" },

  // 81-90: Wheel of Time (The Forsaken & Dragons)
  { level: 81, name: "Lan Mandragoran", emoji: "🗡️", color: "#1e293b" },
  { level: 82, name: "Moiraine Damodred", emoji: "💧", color: "#1d4ed8" },
  { level: 83, name: "Ishamael", emoji: "👁️", color: "#450a0a" },
  { level: 84, name: "Callandor Wielder", emoji: "💎", color: "#22d3ee" },
  { level: 85, name: "Lewes Therin", emoji: "☀️", color: "#fde047" },
  { level: 86, name: "Dragon Reborn", emoji: "🐉", color: "#ef4444" },

  // NEW LEVELS 87-90
  { level: 87, name: "Phoenix Down", emoji: "🪶", color: "#fb7185" },
  { level: 88, name: "Void Sentinel", emoji: "👁️‍🗨️", color: "#4ade80" },
  { level: 89, name: "Elder Wand", emoji: "🪄", color: "#94a3b8" },
  { level: 90, name: "Balrog's Whip", emoji: "🔥", color: "#b91c1c" },

  // 91-100: Cosmic Legends
  { level: 91, name: "Sauron's Shadow", emoji: "👁️", color: "#000000" },
  { level: 92, name: "Galadriel's Light", emoji: "🌟", color: "#e2e8f0" },
  { level: 93, name: "Eldrazi Titan", emoji: "🐙", color: "#a855f7" },
  { level: 94, name: "Tom Bombadil", emoji: "🍄", color: "#fbbf24" },
  { level: 95, name: "Sauron Unleashed", emoji: "🌋", color: "#7f1d1d" },
  { level: 96, name: "Saruman the White", emoji: "✋", color: "#cbd5e1" },
  { level: 97, name: "Gandalf the Grey", emoji: "🎆", color: "#64748b" },
  { level: 98, name: "Gandalf the White", emoji: "🧙‍♂️", color: "#ffffff" },
  { level: 99, name: "The Creator", emoji: "🌌", color: "#6366f1" },
  { level: 100, name: "Eru Ilúvatar", emoji: "✨", color: "#ffffff" },

  { level: 101, name: "Padawan Learner", emoji: "🧘", color: "#60a5fa" },
  { level: 102, name: "Moisture Farmer", emoji: "🚜", color: "#d97706" },
  { level: 103, name: "Scrappy Scavenger", emoji: "🔧", color: "#fcd34d" },
  { level: 104, name: "Cantina Regular", emoji: "🍹", color: "#9333ea" },
  { level: 105, name: "Holocron Finder", emoji: "🧊", color: "#38bdf8" },
  { level: 106, name: "Speeder Racer", emoji: "🏎️", color: "#fb923c" },
  { level: 107, name: "Droid Mechanic", emoji: "🤖", color: "#94a3b8" },
  { level: 108, name: "Kyber Seeker", emoji: "💎", color: "#ffffff" },
  { level: 109, name: "Outer Rim Nomad", emoji: "🏜️", color: "#a8a29e" },
  { level: 110, name: "Rebel Pilot", emoji: "🚀", color: "#ef4444" },
  { level: 111, name: "Squadron Leader", emoji: "📡", color: "#f87171" },
  { level: 112, name: "Astromech Specialist", emoji: "🔌", color: "#3b82f6" },
  { level: 113, name: "Smuggler Associate", emoji: "📦", color: "#b45309" },
  { level: 114, name: "Sabacc Champion", emoji: "🃏", color: "#fbbf24" },
  { level: 115, name: "Jedi Knight", emoji: "⚔️", color: "#60a5fa" },
  { level: 116, name: "Lightsaber Smith", emoji: "🛠️", color: "#2dd4bf" },
  { level: 117, name: "Force Sensitive", emoji: "🌀", color: "#818cf8" },
  { level: 118, name: "Temple Guardian", emoji: "🏰", color: "#facc15" },
  { level: 119, name: "Wayseeker", emoji: "🧭", color: "#94a3b8" },
  { level: 120, name: "Mandalorian Initiate", emoji: "🛡️", color: "#64748b" },
  { level: 121, name: "Foundling", emoji: "👶", color: "#cbd5e1" },
  { level: 122, name: "Beskar Bearer", emoji: "🌑", color: "#475569" },
  { level: 123, name: "Clan Defender", emoji: "⚔️", color: "#1e293b" },
  { level: 124, name: "Jetpack Ace", emoji: "🔥", color: "#f97316" },
  { level: 125, name: "Jedi Guardian", emoji: "🛡️", color: "#22c55e" },

  // --- IMPERIAL MIGHT: THE SHADOW (126-150) ---
  { level: 126, name: "Stormtrooper Recruit", emoji: "⚪", color: "#ffffff" },
  { level: 127, name: "Scout Trooper", emoji: "🏍️", color: "#e2e8f0" },
  { level: 128, name: "TIE Pilot", emoji: "🦇", color: "#1f2937" },
  { level: 129, name: "Imperial Officer", emoji: "💂", color: "#334155" },
  { level: 130, name: "Millennium Captain", emoji: "🌌", color: "#fbbf24" },
  { level: 131, name: "Sith Acolyte", emoji: "💀", color: "#991b1b" },
  { level: 132, name: "Shadow Guard", emoji: "👤", color: "#000000" },
  { level: 133, name: "Inquisitor Trainee", emoji: "🔴", color: "#dc2626" },
  { level: 134, name: "Purge Trooper", emoji: "🧨", color: "#450a0a" },
  { level: 135, name: "Sith Stalker", emoji: "🕵️", color: "#7f1d1d" },
  { level: 136, name: "Red Guard", emoji: "🛡️", color: "#b91c1c" },
  { level: 137, name: "Dark Side Adept", emoji: "🌑", color: "#450606" },
  { level: 138, name: "Sith Alchemist", emoji: "🧪", color: "#6d28d9" },
  { level: 139, name: "Holocron Corruptor", emoji: "🔻", color: "#be123c" },
  { level: 140, name: "Imperial Inquisitor", emoji: "🤺", color: "#991b1b" },
  { level: 141, name: "Grand Inquisitor", emoji: "👹", color: "#7f1d1d" },
  {
    level: 142,
    name: "Star Destroyer Commander",
    emoji: "🚢",
    color: "#94a3b8",
  },
  {
    level: 143,
    name: "Super Star Destroyer Admin",
    emoji: "📐",
    color: "#64748b",
  },
  {
    level: 144,
    name: "Kyber Crystal Corruptor",
    emoji: "🩸",
    color: "#f43f5e",
  },
  { level: 145, name: "Death Star Architect", emoji: "🛰️", color: "#475569" },
  { level: 146, name: "Planetary Governor", emoji: "🪐", color: "#ca8a04" },
  { level: 147, name: "Imperial Advisor", emoji: "🧠", color: "#a855f7" },
  { level: 148, name: "Sith Warrior", emoji: "⚔️", color: "#991b1b" },
  { level: 149, name: "Dark Disciple", emoji: "🔥", color: "#dc2626" },
  { level: 150, name: "Sith Lord", emoji: "😈", color: "#000000" },

  // --- BOUNTY HUNTERS & MERCENARIES (151-175) ---
  { level: 151, name: "Guild Member", emoji: "📜", color: "#8b5e3c" },
  { level: 152, name: "Tracker", emoji: "👣", color: "#a8a29e" },
  { level: 153, name: "Sniper Specialist", emoji: "🎯", color: "#ef4444" },
  {
    level: 154,
    name: "Thermal Detonator Expert",
    emoji: "💣",
    color: "#f97316",
  },
  { level: 155, name: "Bounty Hunter Prime", emoji: "🎖️", color: "#4ade80" },
  { level: 156, name: "Carbonite Freezer", emoji: "🧊", color: "#bae6fd" },
  { level: 157, name: "Underworld Kingpin", emoji: "👑", color: "#7c3aed" },
  { level: 158, name: "Hutt Enforcer", emoji: "🐌", color: "#65a30d" },
  { level: 159, name: "Crime Syndicate Boss", emoji: "💼", color: "#1e1b4b" },
  { level: 160, name: "Grand Moff", emoji: "🏅", color: "#334155" },
  { level: 161, name: "Imperial Regent", emoji: "🏛️", color: "#94a3b8" },
  { level: 162, name: "Hand of Justice", emoji: "⚖️", color: "#facc15" },
  { level: 163, name: "Ancient Archivist", emoji: "📚", color: "#d97706" },
  { level: 164, name: "Dathomir Witch", emoji: "🔮", color: "#db2777" },
  { level: 165, name: "Grey Jedi", emoji: "☯️", color: "#64748b" },
  { level: 166, name: "Balance Seeker", emoji: "🌓", color: "#94a3b8" },
  { level: 167, name: "Jedi Master", emoji: "🧘", color: "#60a5fa" },
  { level: 168, name: "Council Member", emoji: "🪑", color: "#3b82f6" },
  { level: 169, name: "Temple Overseer", emoji: "🏛️", color: "#2563eb" },
  { level: 170, name: "Jedi Sage", emoji: "📜", color: "#93c5fd" },
  { level: 171, name: "High Republic Hero", emoji: "🌟", color: "#fbbf24" },
  { level: 172, name: "Living Force Vessel", emoji: "🍃", color: "#4ade80" },
  { level: 173, name: "Chosen One Initiate", emoji: "⚡", color: "#ffffff" },
  { level: 174, name: "Master of the Order", emoji: "👑", color: "#1d4ed8" },
  { level: 175, name: "Jedi Grand Master", emoji: "🧘‍♂️", color: "#10b981" },

  // --- THE FORCE SUPREME (176-200) ---
  { level: 176, name: "Dark Side Entity", emoji: "🌑", color: "#111827" },
  { level: 177, name: "Life Force Leecher", emoji: "🩸", color: "#7f1d1d" },
  { level: 178, name: "Sith Emperor", emoji: "👑", color: "#000000" },
  { level: 179, name: "World Eater", emoji: "🌎", color: "#4c0519" },
  { level: 180, name: "Darth Vader's Wrath", emoji: "👺", color: "#b91c1c" },
  { level: 181, name: "Unstoppable Force", emoji: "🌪️", color: "#ffffff" },
  { level: 182, name: "Immovable Object", emoji: "🗿", color: "#475569" },
  { level: 183, name: "Force Projection", emoji: "✨", color: "#7dd3fc" },
  { level: 184, name: "Voice of the Force", emoji: "🗣️", color: "#e2e8f0" },
  { level: 185, name: "Emperor's Hand", emoji: "⚡", color: "#a855f7" },
  { level: 186, name: "Force Stormbringer", emoji: "🌩️", color: "#38bdf8" },
  { level: 187, name: "Space-Time Weaver", emoji: "🕸️", color: "#c084fc" },
  {
    level: 188,
    name: "World Between Worlds Explorer",
    emoji: "🌌",
    color: "#a5b4fc",
  },
  { level: 189, name: "Cosmic Sentinel", emoji: "👁️", color: "#2dd4bf" },
  { level: 190, name: "Force Ghost", emoji: "👻", color: "#bae6fd" },
  { level: 191, name: "Ethereal Guide", emoji: "🕯️", color: "#ffffff" },
  { level: 192, name: "Midi-chlorian Master", emoji: "🧬", color: "#4ade80" },
  { level: 193, name: "Force Nexus", emoji: "🔆", color: "#facc15" },
  { level: 194, name: "Ancient One", emoji: "⏳", color: "#d97706" },
  { level: 195, name: "The Son & The Daughter", emoji: "☯️", color: "#000000" },
  { level: 196, name: "Avatar of Mortis", emoji: "🏛️", color: "#f8fafc" },
  { level: 197, name: "Bendu's Wisdom", emoji: "🐂", color: "#78350f" },
  { level: 198, name: "The Father", emoji: "⚖️", color: "#fbbf24" },
  { level: 199, name: "The Whills", emoji: "👁️", color: "#5eead4" },
  { level: 200, name: "One With The Force", emoji: "🌌", color: "#ffffff" },
  // --- CYBERPUNK & FUTURE TECH (201-225) ---
  { level: 201, name: "Chrome Junkie", emoji: "🦾", color: "#64748b" },
  { level: 202, name: "Data Courier", emoji: "💾", color: "#94a3b8" },
  { level: 203, name: "Street Samurai", emoji: "⚔️", color: "#f43f5e" },
  { level: 204, name: "Braindance Tuner", emoji: "🧠", color: "#a855f7" },
  { level: 205, name: "Ripperdoc Apprentice", emoji: "💉", color: "#10b981" },
  { level: 206, name: "Neural Linker", emoji: "🕸️", color: "#22d3ee" },
  { level: 207, name: "Grid Runner", emoji: "🏃", color: "#38bdf8" },
  { level: 208, name: "Sub-Grid Ghost", emoji: "👻", color: "#6366f1" },
  { level: 209, name: "Black Ice Specialist", emoji: "🧊", color: "#1d4ed8" },
  { level: 210, name: "Netrunner", emoji: "🔌", color: "#06b6d4" },
  { level: 211, name: "System Infiltrator", emoji: "🔓", color: "#fbbf24" },
  { level: 212, name: "Mainframe Ghost", emoji: "💻", color: "#f8fafc" },
  { level: 213, name: "Cyberdeck Modder", emoji: "🛠️", color: "#475569" },
  { level: 214, name: "Neon Nomad", emoji: "🏜️", color: "#f59e0b" },
  { level: 215, name: "Night City Fixer", emoji: "📞", color: "#ec4899" },
  { level: 216, name: "Corporate Saboteur", emoji: "💼", color: "#1e293b" },
  { level: 217, name: "Technomancer", emoji: "🪄", color: "#8b5e3c" },
  { level: 218, name: "Synthwave Rider", emoji: "🌅", color: "#f472b6" },
  { level: 219, name: "Memory Dealer", emoji: "🧠", color: "#a78bfa" },
  { level: 220, name: "Glitch Hunter", emoji: "👾", color: "#22c55e" },
  { level: 221, name: "Firewall Breaker", emoji: "🔥", color: "#ef4444" },
  { level: 222, name: "Protocol Enforcer", emoji: "🛡️", color: "#3b82f6" },
  { level: 223, name: "AI Whisperer", emoji: "🤖", color: "#f97316" },
  { level: 224, name: "Bio-Hacker", emoji: "🧬", color: "#84cc16" },
  { level: 225, name: "The Ghost in the Shell", emoji: "🐚", color: "#ffffff" },

  // --- THE MATRIX & SIMULATION (226-250) ---
  { level: 226, name: "Blue Pill Resident", emoji: "💊", color: "#3b82f6" },
  { level: 227, name: "Red Pill Awakened", emoji: "💊", color: "#ef4444" },
  { level: 228, name: "Zion Operator", emoji: "🎧", color: "#166534" },
  { level: 229, name: "Code Construct", emoji: "🏗️", color: "#22c55e" },
  { level: 230, name: "Sentinel Dodger", emoji: "🦑", color: "#475569" },
  { level: 231, name: "Nebuchadnezzar Crew", emoji: "🚢", color: "#94a3b8" },
  { level: 232, name: "Simulation Glitch", emoji: "📺", color: "#a855f7" },
  { level: 233, name: "Bullet-Time Master", emoji: "🔫", color: "#ffffff" },
  { level: 234, name: "Agent Program", emoji: "🕶️", color: "#111827" },
  { level: 235, name: "Rogue Program", emoji: "🚫", color: "#991b1b" },
  { level: 236, name: "The Keymaker", emoji: "🔑", color: "#fbbf24" },
  { level: 237, name: "Merovingian Guard", emoji: "🍷", color: "#7f1d1d" },
  { level: 238, name: "The Oracle's Pupil", emoji: "🍪", color: "#d97706" },
  { level: 239, name: "Seraph's Equal", emoji: "🕊️", color: "#f8fafc" },
  { level: 240, name: "Source Architect", emoji: "🏛️", color: "#ffffff" },
  { level: 241, name: "Logic Bomb", emoji: "💣", color: "#000000" },
  { level: 242, name: "Digital Messiah", emoji: "✨", color: "#6366f1" },
  { level: 243, name: "Binary Sovereign", emoji: "🔢", color: "#22c55e" },
  { level: 244, name: "Hardware Overlord", emoji: "🔌", color: "#4b5563" },
  { level: 245, name: "Recursive Soul", emoji: "🌀", color: "#8b5e3c" },
  { level: 246, name: "Data Streamer", emoji: "🌊", color: "#0ea5e9" },
  { level: 247, name: "Packet Sniffer", emoji: "👃", color: "#64748b" },
  { level: 248, name: "Root Admin", emoji: "🌳", color: "#15803d" },
  { level: 249, name: "The One", emoji: "🕴️", color: "#000000" },
  { level: 250, name: "The Source", emoji: "🔆", color: "#ffffff" },

  // --- ANIME: THE SHONEN PATH (251-275) ---
  { level: 251, name: "Academy Student", emoji: "🎒", color: "#f97316" },
  { level: 252, name: "Leaf Village Genin", emoji: "🍃", color: "#16a34a" },
  { level: 253, name: "Chunin Candidate", emoji: "📜", color: "#b45309" },
  { level: 254, name: "Jonin Elite", emoji: "🧥", color: "#14532d" },
  { level: 255, name: "Anbu Black Ops", emoji: "🎭", color: "#334155" },
  { level: 256, name: "Sannin Successor", emoji: "🐸", color: "#22c55e" },
  { level: 257, name: "Kage", emoji: "🏮", color: "#dc2626" },
  { level: 258, name: "Tailed Beast Host", emoji: "🦊", color: "#f97316" },
  { level: 259, name: "Sage Mode", emoji: "👁️", color: "#fbbf24" },
  { level: 260, name: "Super Saiyan", emoji: "👱", color: "#facc15" },
  { level: 261, name: "Ascended Saiyan", emoji: "⚡", color: "#ffffff" },
  { level: 262, name: "Z-Fighter", emoji: "🥋", color: "#ea580c" },
  { level: 263, name: "Namekian Healer", emoji: "💊", color: "#16a34a" },
  { level: 264, name: "Gravity Trainer", emoji: "🏋️", color: "#475569" },
  { level: 265, name: "Spirit Bomb User", emoji: "🔵", color: "#3b82f6" },
  { level: 266, name: "God of Destruction", emoji: "🟣", color: "#a855f7" },
  { level: 267, name: "Ultra Instinct", emoji: "🥈", color: "#e2e8f0" },
  { level: 268, name: "Soul Reaper", emoji: "💀", color: "#000000" },
  { level: 269, name: "Shikai Awakened", emoji: "⚔️", color: "#94a3b8" },
  { level: 270, name: "Bankai Master", emoji: "💥", color: "#991b1b" },
  { level: 271, name: "Captain of Squad 13", emoji: "🧥", color: "#ffffff" },
  { level: 272, name: "Hollow Mask", emoji: "👹", color: "#dc2626" },
  { level: 273, name: "Quincy Archer", emoji: "🏹", color: "#38bdf8" },
  { level: 274, name: "Espada Rank", emoji: "🔢", color: "#1e293b" },
  { level: 275, name: "Number One Protector", emoji: "🛡️", color: "#facc15" },

  // --- ANIME: GRAND LINE VOYAGERS (276-300) ---
  { level: 276, name: "East Blue Cabin Boy", emoji: "🧹", color: "#94a3b8" },
  { level: 277, name: "Devil Fruit Eater", emoji: "🍇", color: "#a855f7" },
  { level: 278, name: "Grand Line Navigator", emoji: "🧭", color: "#3b82f6" },
  { level: 279, name: "Sniper King", emoji: "👺", color: "#facc15" },
  { level: 280, name: "Black Leg Chef", emoji: "🍳", color: "#1e293b" },
  { level: 281, name: "Santoryu Master", emoji: "⚔️", color: "#16a34a" },
  { level: 282, name: "Cyborg Shipwright", emoji: "🔧", color: "#06b6d4" },
  { level: 283, name: "Archaeologist", emoji: "🏺", color: "#8b5e3c" },
  {
    level: 284,
    name: "Doctor of Cherry Blossoms",
    emoji: "🌸",
    color: "#f472b6",
  },
  { level: 285, name: "Warlord of the Sea", emoji: "🏴‍☠️", color: "#7f1d1d" },
  { level: 286, name: "Haki User", emoji: "🌑", color: "#334155" },
  { level: 287, name: "Conqueror's Spirit", emoji: "👑", color: "#991b1b" },
  { level: 288, name: "Supernova", emoji: "🌟", color: "#fbbf24" },
  { level: 289, name: "Revolutionary", emoji: "🚩", color: "#dc2626" },
  { level: 290, name: "Yonko Commander", emoji: "🎖️", color: "#4c0519" },
  { level: 291, name: "Emperor of the Sea", emoji: "🍷", color: "#7f1d1d" },
  { level: 292, name: "Ancient Weapon Seeker", emoji: "🔱", color: "#22d3ee" },
  { level: 293, name: "Gear Second", emoji: "💨", color: "#f87171" },
  { level: 294, name: "Gear Fourth", emoji: "🦍", color: "#991b1b" },
  { level: 295, name: "Joy Boy Heir", emoji: "🌞", color: "#ffffff" },
  { level: 296, name: "Logia Intangible", emoji: "🌫️", color: "#e2e8f0" },
  { level: 297, name: "Admiral of the Fleet", emoji: "⚓", color: "#ffffff" },
  { level: 298, name: "Laugh Tale Voyager", emoji: "🗺️", color: "#fbbf24" },
  { level: 299, name: "Pirate King", emoji: "🏴‍☠️", color: "#ef4444" },
  { level: 300, name: "King of the World", emoji: "🌎", color: "#ffffff" },

  // --- DUNGEONS & DRAGONS: THE ADVENTURE BEGINS (301-325) ---
  { level: 301, name: "Tavern Patron", emoji: "🍺", color: "#92400e" },
  { level: 302, name: "Quest Board Reader", emoji: "📜", color: "#d97706" },
  { level: 303, name: "Goblin Slayer", emoji: "👺", color: "#166534" },
  { level: 304, name: "Dungeon Delver", emoji: "🔦", color: "#475569" },
  { level: 305, name: "Loot Hoarder", emoji: "💰", color: "#fbbf24" },
  { level: 306, name: "Natural 1 Survivor", emoji: "🎲", color: "#ef4444" },
  { level: 307, name: "Critical Success", emoji: "✨", color: "#facc15" },
  { level: 308, name: "Bardic Inspiration", emoji: "🪕", color: "#ec4899" },
  { level: 309, name: "Paladin's Oath", emoji: "🛡️", color: "#ffffff" },
  { level: 310, name: "Eldritch Blaster", emoji: "🪄", color: "#a855f7" },
  { level: 311, name: "Wild Shape Druid", emoji: "🐻", color: "#22c55e" },
  { level: 312, name: "Sneak Attack Rogue", emoji: "🗡️", color: "#1e293b" },
  { level: 313, name: "Rage-Fueled Barbarian", emoji: "🪓", color: "#991b1b" },
  { level: 314, name: "Fireball Enthusiast", emoji: "🔥", color: "#f97316" },
  { level: 315, name: "Circle of the Moon", emoji: "🌙", color: "#94a3b8" },
  { level: 316, name: "Bag of Holding", emoji: "👜", color: "#8b5e3c" },
  { level: 317, name: "Mimic Victim", emoji: "📦", color: "#7f1d1d" },
  { level: 318, name: "Beholder Stare", emoji: "👁️", color: "#4c0519" },
  { level: 319, name: "Lich's Phylactery", emoji: "🏺", color: "#c084fc" },
  { level: 320, name: "Tiamat's Chosen", emoji: "🐲", color: "#dc2626" },
  { level: 321, name: "Ancient Red Dragon", emoji: "🐉", color: "#b91c1c" },
  { level: 322, name: "Vorpal Blade Wielder", emoji: "⚔️", color: "#e2e8f0" },
  { level: 323, name: "Wish Spellcaster", emoji: "🧞", color: "#38bdf8" },
  { level: 324, name: "Dungeon Master", emoji: "🏰", color: "#000000" },
  { level: 325, name: "The Rule of Cool", emoji: "😎", color: "#ffffff" },

  // --- THE WITCHER & MONSTER HUNTERS (326-350) ---
  { level: 326, name: "Trial of the Grasses", emoji: "🌿", color: "#16a34a" },
  { level: 327, name: "School of the Wolf", emoji: "🐺", color: "#475569" },
  { level: 328, name: "School of the Cat", emoji: "🐈", color: "#94a3b8" },
  { level: 329, name: "School of the Griffin", emoji: "🦅", color: "#fbbf24" },
  { level: 330, name: "Silver Sword Master", emoji: "🗡️", color: "#cbd5e1" },
  { level: 331, name: "Steel Sword Master", emoji: "⚔️", color: "#1e293b" },
  { level: 332, name: "Igni Sign", emoji: "🔥", color: "#ef4444" },
  { level: 333, name: "Quen Shield", emoji: "🟡", color: "#facc15" },
  { level: 334, name: "Aard Blast", emoji: "💨", color: "#38bdf8" },
  { level: 335, name: "Axii Charm", emoji: "🌀", color: "#a855f7" },
  { level: 336, name: "Yrden Trap", emoji: "🔯", color: "#6366f1" },
  { level: 337, name: "Thunderbolt Potion", emoji: "🧪", color: "#22c55e" },
  { level: 338, name: "Blizzard Reflexes", emoji: "❄️", color: "#bae6fd" },
  { level: 339, name: "Gwent Grandmaster", emoji: "🃏", color: "#d97706" },
  { level: 340, name: "Butcher of Blaviken", emoji: "🩸", color: "#7f1d1d" },
  { level: 341, name: "Wild Hunt Rider", emoji: "💀", color: "#0f172a" },
  { level: 342, name: "Ciri's Resolve", emoji: "💍", color: "#64748b" },
  { level: 343, name: "Elder Blood Heir", emoji: "🧬", color: "#ffffff" },
  { level: 344, name: "Conjunction of Spheres", emoji: "🪐", color: "#4c0519" },
  {
    level: 345,
    name: "Gaunter O'Dimm's Debtor",
    emoji: "⏳",
    color: "#000000",
  },
  { level: 346, name: "Master of Mirrors", emoji: "🪞", color: "#facc15" },
  { level: 347, name: "Leshen Stalker", emoji: "🦌", color: "#14532d" },
  { level: 348, name: "Higher Vampire", emoji: "🧛", color: "#450a0a" },
  { level: 349, name: "White Wolf Legend", emoji: "🐺", color: "#ffffff" },
  { level: 350, name: "The Witcher Path", emoji: "🛤️", color: "#8b5e3c" },

  // --- THE ELDER SCROLLS: TAMRIEL LEGENDS (351-400) ---
  { level: 351, name: "Sweetroll Thief", emoji: "🥐", color: "#d97706" },
  { level: 352, name: "Arrow to the Knee", emoji: "🏹", color: "#94a3b8" },
  { level: 353, name: "Mages Guild Associate", emoji: "🔮", color: "#6366f1" },
  { level: 354, name: "Fighters Guild Hero", emoji: "⚔️", color: "#b45309" },
  { level: 355, name: "Thieves Guild Shadow", emoji: "👤", color: "#1e293b" },
  {
    level: 356,
    name: "Dark Brotherhood Assassin",
    emoji: "🖐️",
    color: "#991b1b",
  },
  { level: 357, name: "Nightmother's Listener", emoji: "👂", color: "#000000" },
  { level: 358, name: "Gray Fox", emoji: "🦊", color: "#475569" },
  { level: 359, name: "Gray Cowl Bearer", emoji: "🎭", color: "#64748b" },
  { level: 360, name: "Champion of Cyrodiil", emoji: "🛡️", color: "#fbbf24" },
  { level: 361, name: "Hero of Kvatch", emoji: "🔥", color: "#dc2626" },
  { level: 362, name: "Shivering Isles Ruler", emoji: "🧀", color: "#a855f7" },
  { level: 363, name: "Sheogorath's Sanity", emoji: "🤪", color: "#f472b6" },
  { level: 364, name: "Dragonborn Initiate", emoji: "🐉", color: "#ffffff" },
  { level: 365, name: "Unrelenting Force", emoji: "🗣️", color: "#38bdf8" },
  { level: 366, name: "Fus Ro Dah", emoji: "💥", color: "#ffffff" },
  { level: 367, name: "Whiterun Thane", emoji: "🏰", color: "#15803d" },
  { level: 368, name: "Stormcloak Rebel", emoji: "🐻", color: "#1d4ed8" },
  { level: 369, name: "Imperial Legionnaire", emoji: "🏛️", color: "#ef4444" },
  {
    level: 370,
    name: "Arch-Mage of Winterhold",
    emoji: "🧙",
    color: "#c084fc",
  },
  { level: 371, name: "Black Star Owner", emoji: "⭐", color: "#000000" },
  { level: 372, name: "Mehrunes' Razor", emoji: "🗡️", color: "#991b1b" },
  { level: 373, name: "Mace of Molag Bal", emoji: "🔨", color: "#4c0519" },
  { level: 374, name: "Skeleton Key Master", emoji: "🔑", color: "#22d3ee" },
  { level: 375, name: "Nightingale Sentinel", emoji: "🌙", color: "#1e293b" },
  { level: 376, name: "Alduin's Bane", emoji: "🐲", color: "#000000" },
  { level: 377, name: "Sovngarde Warrior", emoji: "🍺", color: "#fbbf24" },
  { level: 378, name: "Nerevarine Prophecy", emoji: "💍", color: "#d97706" },
  { level: 379, name: "Moon-and-Star", emoji: "🌙", color: "#facc15" },
  { level: 380, name: "Tribunal Member", emoji: "🏛️", color: "#6366f1" },
  { level: 381, name: "Vivec's Poet", emoji: "📜", color: "#fbbf24" },
  { level: 382, name: "Dagoth Ur's Dreamer", emoji: "👺", color: "#991b1b" },
  { level: 383, name: "Heart of Lorkhan", emoji: "❤️", color: "#7f1d1d" },
  { level: 384, name: "Sixth House Apostle", emoji: "🔔", color: "#450a0a" },
  { level: 385, name: "The Elder Scroll", emoji: "📜", color: "#ffffff" },
  { level: 386, name: "Anu & Padomay", emoji: "☯️", color: "#64748b" },
  { level: 387, name: "Akatosh's Breath", emoji: "⏳", color: "#facc15" },
  { level: 388, name: "Aedric Spirit", emoji: "✨", color: "#ffffff" },
  { level: 389, name: "Daedric Prince", emoji: "👑", color: "#000000" },
  { level: 390, name: "Azura's Wisdom", emoji: "💎", color: "#3b82f6" },
  {
    level: 391,
    name: "Hermaeus Mora's Knowledge",
    emoji: "🐙",
    color: "#166534",
  },
  { level: 392, name: "Nocturnal's Luck", emoji: "🐦", color: "#1e1b4b" },
  { level: 393, name: "Sanguine's Revelry", emoji: "🍷", color: "#ec4899" },
  { level: 394, name: "Boethiah's Betrayal", emoji: "🗡️", color: "#7f1d1d" },
  { level: 395, name: "Peryite's Plague", emoji: "🤢", color: "#84cc16" },
  { level: 396, name: "Namira's Hunger", emoji: "🦴", color: "#451a03" },
  { level: 397, name: "Hircine's Hunt", emoji: "🐺", color: "#b45309" },
  { level: 398, name: "CHIM Awakener", emoji: "🌌", color: "#a855f7" },
  { level: 399, name: "The Amaranth", emoji: "💤", color: "#ffffff" },
  { level: 400, name: "Reality Modder", emoji: "🛠️", color: "#22c55e" },

  // --- MARVEL & DC: THE COSMIC HEROES (401-425) ---
  { level: 401, name: "Street Vigilante", emoji: "👊", color: "#475569" },
  { level: 402, name: "Gamma Radiated", emoji: "🤢", color: "#16a34a" },
  { level: 403, name: "Super Soldier", emoji: "🛡️", color: "#1d4ed8" },
  { level: 404, name: "Genius Billionaire", emoji: "🦾", color: "#ef4444" },
  { level: 405, name: "God of Thunder", emoji: "⚡", color: "#38bdf8" },
  { level: 406, name: "Sorcerer Supreme", emoji: "👁️", color: "#7c3aed" },
  { level: 407, name: "Web Slinger", emoji: "🕸️", color: "#dc2626" },
  { level: 408, name: "Wakandan Warrior", emoji: "🐾", color: "#1e293b" },
  { level: 409, name: "Man of Steel", emoji: "🦸", color: "#2563eb" },
  { level: 410, name: "Dark Knight", emoji: "🦇", color: "#000000" },
  { level: 411, name: "Amazonian Princess", emoji: "👑", color: "#b91c1c" },
  { level: 412, name: "Emerald Knight", emoji: "💍", color: "#10b981" },
  { level: 413, name: "Speed Force Runner", emoji: "⚡", color: "#facc15" },
  { level: 414, name: "Atlantian King", emoji: "🔱", color: "#06b6d4" },
  { level: 415, name: "Martian Manhunter", emoji: "👽", color: "#15803d" },
  { level: 416, name: "Anti-Hero", emoji: "💀", color: "#4b5563" },
  { level: 417, name: "Infinity Stone Keeper", emoji: "💎", color: "#ec4899" },
  {
    level: 418,
    name: "Infinity Gauntlet Wielder",
    emoji: "🧤",
    color: "#fbbf24",
  },
  { level: 419, name: "Herald of Galactus", emoji: "🏄", color: "#cbd5e1" },
  { level: 420, name: "World Eater", emoji: "🌑", color: "#4c0519" },
  { level: 421, name: "Phoenix Force", emoji: "🔥", color: "#f97316" },
  { level: 422, name: "Watchmen's Insight", emoji: "⏱️", color: "#facc15" },
  { level: 423, name: "Doctor Manhattan", emoji: "⚛️", color: "#3b82f6" },
  { level: 424, name: "The Living Tribunal", emoji: "🎭", color: "#fbbf24" },
  { level: 425, name: "One-Above-All", emoji: "✨", color: "#ffffff" },

  // --- SCI-FI CLASSICS: SPACE & TIME (426-450) ---
  { level: 426, name: "Starfleet Cadet", emoji: "🖖", color: "#fde047" },
  { level: 427, name: "Vulcan Logician", emoji: "🧠", color: "#3b82f6" },
  { level: 428, name: "Borg Collective", emoji: "🤖", color: "#166534" },
  { level: 429, name: "Spice Smuggler", emoji: "🏜️", color: "#b45309" },
  { level: 430, name: "Kwisatz Haderach", emoji: "👁️", color: "#312e81" },
  { level: 431, name: "Shai-Hulud Rider", emoji: "🪱", color: "#d97706" },
  { level: 432, name: "HAL 9000 Logic", emoji: "🔴", color: "#ef4444" },
  { level: 433, name: "Stargate Traveler", emoji: "🌀", color: "#38bdf8" },
  { level: 434, name: "Xenomorph Stalker", emoji: "👽", color: "#0f172a" },
  { level: 435, name: "Predator Hunter", emoji: "🎯", color: "#14532d" },
  { level: 436, name: "Deckard's Memory", emoji: "🦄", color: "#94a3b8" },
  { level: 437, name: "Time Lord", emoji: "⏳", color: "#7c3aed" },
  { level: 438, name: "TARDIS Pilot", emoji: "🟦", color: "#1d4ed8" },
  { level: 439, name: "Cyberman", emoji: "🦾", color: "#cbd5e1" },
  { level: 440, name: "Dalek Supreme", emoji: "🚽", color: "#b91c1c" },
  {
    level: 441,
    name: "Foundation Psycho-Historian",
    emoji: "📚",
    color: "#475569",
  },
  { level: 442, name: "Neuromancer", emoji: "💻", color: "#ec4899" },
  { level: 443, name: "Wintermute", emoji: "❄️", color: "#ffffff" },
  { level: 444, name: "The Overmind", emoji: "🧠", color: "#a855f7" },
  { level: 445, name: "Multiverse Anchor", emoji: "⚓", color: "#6366f1" },
  { level: 446, name: "Event Horizon Survivor", emoji: "🕳️", color: "#000000" },
  { level: 447, name: "Hyperion Shrike", emoji: "🌵", color: "#4b5563" },
  { level: 448, name: "The Culture Mind", emoji: "🛰️", color: "#ffffff" },
  { level: 449, name: "Type III Civilization", emoji: "🌌", color: "#fbbf24" },
  { level: 450, name: "End of Eternity", emoji: "♾️", color: "#ffffff" },

  // --- ELDRITCH HORRORS & THE VOID (451-475) ---
  { level: 451, name: "Miskatonic Professor", emoji: "📖", color: "#451a03" },
  { level: 452, name: "Elder Sign Carver", emoji: "🔯", color: "#3b82f6" },
  { level: 453, name: "Cult of Cthulhu", emoji: "🐙", color: "#064e3b" },
  { level: 454, name: "Deep One Hybrid", emoji: "🐟", color: "#065f46" },
  { level: 455, name: "Shadow Over Innsmouth", emoji: "🌫️", color: "#94a3b8" },
  { level: 456, name: "The Color Out of Space", emoji: "🌈", color: "#d8b4fe" },
  { level: 457, name: "Dunwich Horror", emoji: "🐐", color: "#78350f" },
  { level: 458, name: "Shoggoth Form", emoji: "🦠", color: "#14532d" },
  { level: 459, name: "Nyarlathotep's Avatar", emoji: "👤", color: "#000000" },
  { level: 460, name: "The Black Pharaoh", emoji: "🏺", color: "#fbbf24" },
  { level: 461, name: "Crawling Chaos", emoji: "🐜", color: "#1e293b" },
  { level: 462, name: "King in Yellow", emoji: "👑", color: "#facc15" },
  { level: 463, name: "Hastur's Sign", emoji: "🟡", color: "#f59e0b" },
  { level: 464, name: "The Nameless City", emoji: "🏛️", color: "#8b5e3c" },
  { level: 465, name: "Outer God Envoy", emoji: "🛸", color: "#ffffff" },
  { level: 466, name: "Shub-Niggurath Spawn", emoji: "🌲", color: "#064e3b" },
  { level: 467, name: "Yog-Sothoth's Gate", emoji: "🗝️", color: "#a855f7" },
  { level: 468, name: "The Key and the Gate", emoji: "🌀", color: "#6366f1" },
  { level: 469, name: "Azathoth's Dreamer", emoji: "💤", color: "#ffffff" },
  { level: 470, name: "Blind Idiot God", emoji: "🥁", color: "#000000" },
  { level: 471, name: "The Void Walker", emoji: "🚶", color: "#0f172a" },
  { level: 472, name: "Entropy's Child", emoji: "📉", color: "#991b1b" },
  { level: 473, name: "Vacuum Decay", emoji: "🫧", color: "#ffffff" },
  { level: 474, name: "The Great Silence", emoji: "🤐", color: "#475569" },
  { level: 475, name: "The Heat Death", emoji: "🧊", color: "#0ea5e9" },

  // --- META-REALITY & THE ARCHITECTS (476-500) ---
  { level: 476, name: "Simulation Theory", emoji: "💻", color: "#22c55e" },
  { level: 477, name: "NPC Self-Awareness", emoji: "🧍", color: "#94a3b8" },
  { level: 478, name: "Source Code Access", emoji: "📝", color: "#10b981" },
  { level: 479, name: "Buffer Overflow", emoji: "🌊", color: "#ef4444" },
  { level: 480, name: "Stack Trace Master", emoji: "🥞", color: "#f97316" },
  { level: 481, name: "Memory Leak", emoji: "💧", color: "#38bdf8" },
  { level: 482, name: "Root Exploit", emoji: "🔓", color: "#dc2626" },
  { level: 483, name: "Zero Day", emoji: "0️⃣", color: "#000000" },
  { level: 484, name: "Kernel Mode", emoji: "🧠", color: "#334155" },
  { level: 485, name: "Ring 0 Access", emoji: "⭕", color: "#ffffff" },
  { level: 486, name: "The Compiler", emoji: "⚙️", color: "#64748b" },
  { level: 487, name: "Garbage Collector", emoji: "🗑️", color: "#84cc16" },
  { level: 488, name: "Deadlock Survivor", emoji: "🔒", color: "#ef4444" },
  { level: 489, name: "Race Condition Runner", emoji: "🏃", color: "#fbbf24" },
  { level: 490, name: "Binary Tree Guardian", emoji: "🌳", color: "#15803d" },
  { level: 491, name: "Recursive God", emoji: "🔄", color: "#6366f1" },
  { level: 492, name: "The Algorithm", emoji: "🧮", color: "#a855f7" },
  {
    level: 493,
    name: "Artificial General Intel",
    emoji: "🧠",
    color: "#ffffff",
  },
  {
    level: 494,
    name: "Technological Singularity",
    emoji: "♾️",
    color: "#ffffff",
  },
  { level: 495, name: "The Developer", emoji: "👨‍💻", color: "#22d3ee" },
  { level: 496, name: "Production Hotfix", emoji: "🩹", color: "#f59e0b" },
  { level: 497, name: "The Git Master", emoji: "🌿", color: "#10b981" },
  { level: 498, name: "Merged into Reality", emoji: "🤝", color: "#ffffff" },
  { level: 499, name: "Final Boss", emoji: "👹", color: "#991b1b" },
  { level: 500, name: "The Creative Director", emoji: "✨", color: "#ffffff" },

  // --- WARHAMMER 40K & GRIMDARK FUTURE (502-525) ---
  {
    level: 501,
    name: "Nurgling Spawn",
    emoji: "🤢",
    color: "#4d7c0f",
  },
  { level: 502, name: "Hive World Scum", emoji: "🏚️", color: "#4b5563" },
  { level: 503, name: "Imperial Guardsman", emoji: "🪖", color: "#166534" },
  { level: 504, name: "Servitor Unit", emoji: "🤖", color: "#94a3b8" },
  { level: 505, name: "Tech-Priest Enginseer", emoji: "⚙️", color: "#991b1b" },
  { level: 506, name: "Adeptus Astartes", emoji: "🛡️", color: "#1d4ed8" },
  { level: 507, name: "Inquisitorial Agent", emoji: "🔍", color: "#7c3aed" },
  { level: 508, name: "Librarian Psyker", emoji: "🔮", color: "#3b82f6" },
  {
    level: 509,
    name: "Exterminatus Authorized",
    emoji: "🔥",
    color: "#ef4444",
  },
  { level: 510, name: "Champion of Chaos", emoji: "👹", color: "#4c0519" },
  { level: 511, name: "Necron Awakened", emoji: "💀", color: "#22c55e" },
  { level: 512, name: "Eldar Farseer", emoji: "💎", color: "#06b6d4" },
  { level: 513, name: "Warp Traveler", emoji: "🌀", color: "#6366f1" },
  { level: 514, name: "Chaos Undivided", emoji: "☸️", color: "#000000" },
  { level: 515, name: "God-Prime Overlord", emoji: "👑", color: "#fbbf24" },
  { level: 516, name: "Eye of Terror Resident", emoji: "👁️", color: "#dc2626" },
  { level: 517, name: "Golden Throne Guardian", emoji: "🕯️", color: "#facc15" },
  { level: 518, name: "Bio-Titan Hunter", emoji: "🦖", color: "#84cc16" },
  { level: 519, name: "Event Horizon Pilot", emoji: "🚀", color: "#1e1b4b" },
  { level: 520, name: "Void Stalker", emoji: "🌑", color: "#0f172a" },
  { level: 521, name: "Cadian Survivor", emoji: "⛰️", color: "#450a0a" },
  { level: 522, name: "Sanguinary Guard", emoji: "🩸", color: "#b91c1c" },
  { level: 523, name: "Omnissiah's Voice", emoji: "📟", color: "#ffffff" },
  { level: 524, name: "Primarch Reborn", emoji: "🏛️", color: "#fbbf24" },
  { level: 525, name: "The Emperor's Will", emoji: "✨", color: "#ffffff" },

  // --- MYTHOLOGY & ANCIENT DIVINITY (526-550) ---
  { level: 526, name: "Styx Ferryman", emoji: "🚣", color: "#475569" },
  { level: 527, name: "Cerberus Tamer", emoji: "🐕", color: "#7f1d1d" },
  { level: 528, name: "Olympian Initiate", emoji: "🏛️", color: "#ffffff" },
  { level: 529, name: "Medusa's Gaze", emoji: "🐍", color: "#166534" },
  { level: 530, name: "Mjolnir Worthy", emoji: "🔨", color: "#38bdf8" },
  { level: 531, name: "Valhalla Resident", emoji: "🍺", color: "#d97706" },
  { level: 532, name: "Valkyrie Flight", emoji: "🦅", color: "#ffffff" },
  { level: 533, name: "Phoenix Rebirth", emoji: "🐦", color: "#f97316" },
  { level: 534, name: "Siren's Call", emoji: "🧜", color: "#06b6d4" },
  { level: 535, name: "Atlas's Burden", emoji: "🌍", color: "#8b5e3c" },
  { level: 536, name: "Prometheus's Flame", emoji: "🔥", color: "#ef4444" },
  { level: 537, name: "Minotaur Labyrinth", emoji: "🐂", color: "#1e293b" },
  { level: 538, name: "Ares's Fury", emoji: "⚔️", color: "#991b1b" },
  { level: 539, name: "Poseidon's Wrath", emoji: "🌊", color: "#1d4ed8" },
  { level: 540, name: "Hades's Silent Prince", emoji: "💎", color: "#000000" },
  { level: 541, name: "Zeus's Thunderbolt", emoji: "⚡", color: "#facc15" },
  { level: 542, name: "Ragnarok Witness", emoji: "🐺", color: "#4c0519" },
  { level: 543, name: "Yggdrasil Climber", emoji: "🌳", color: "#15803d" },
  { level: 544, name: "Fenrir's Unbound", emoji: "⛓️", color: "#4b5563" },
  { level: 545, name: "Osiris's Judgment", emoji: "⚖️", color: "#fbbf24" },
  { level: 546, name: "Anubis's Scale", emoji: "🦝", color: "#1e1b4b" },
  { level: 547, name: "Ra's Solar Chariot", emoji: "☀️", color: "#ffffff" },
  { level: 548, name: "The Titanomachy", emoji: "🏔️", color: "#dc2626" },
  { level: 549, name: "Primordial Chaos", emoji: "🌌", color: "#a855f7" },
  { level: 550, name: "Demi-God Ascension", emoji: "✨", color: "#ffffff" },

  // --- THE QUANTUM REALM & PARTICLE PHYSICS (551-575) ---
  { level: 551, name: "Quark Observer", emoji: "⚛️", color: "#6366f1" },
  { level: 552, name: "Neutrino Drifter", emoji: "👻", color: "#ffffff" },
  { level: 553, name: "Higgs Boson Particle", emoji: "✨", color: "#facc15" },
  { level: 554, name: "Wave-Particle Duality", emoji: "🌊", color: "#38bdf8" },
  { level: 555, name: "Schrödinger’s Cat", emoji: "📦", color: "#4b5563" },
  { level: 556, name: "Quantum Entangler", emoji: "🔗", color: "#a855f7" },
  { level: 557, name: "Superposition Master", emoji: "♊", color: "#10b981" },
  { level: 558, name: "Uncertainty Principle", emoji: "❓", color: "#94a3b8" },
  { level: 559, name: "Quantum Tunneler", emoji: "🕳️", color: "#000000" },
  { level: 560, name: "Plancks Constant", emoji: "📏", color: "#ffffff" },
  { level: 561, name: "Event Horizon Echo", emoji: "📣", color: "#4c0519" },
  { level: 562, name: "String Theory Weaver", emoji: "🧶", color: "#ec4899" },
  {
    level: 563,
    name: "M-Theory Dimensionalist",
    emoji: "📐",
    color: "#22c55e",
  },
  { level: 564, name: "Dark Matter Ghost", emoji: "🌑", color: "#0f172a" },
  { level: 565, name: "Dark Energy Pulse", emoji: "🟣", color: "#7c3aed" },
  { level: 566, name: "Spacetime Fabric Tear", emoji: "🪡", color: "#ef4444" },
  { level: 567, name: "Gravitational Wave", emoji: "〰️", color: "#3b82f6" },
  { level: 568, name: "Wormhole Navigator", emoji: "🌀", color: "#6366f1" },
  { level: 569, name: "Naked Singularity", emoji: "👁️", color: "#ffffff" },
  { level: 570, name: "Cosmic Inflation", emoji: "🎈", color: "#f97316" },
  { level: 571, name: "Hawking Radiation", emoji: "☢️", color: "#fbbf24" },
  { level: 572, name: "Anti-Matter Mirror", emoji: "🪞", color: "#ffffff" },
  { level: 573, name: "Big Bang Echo", emoji: "💥", color: "#dc2626" },
  { level: 574, name: "Thermal Equilibrium", emoji: "⚖️", color: "#22d3ee" },
  { level: 575, name: "Absolute Zero", emoji: "🧊", color: "#ffffff" },

  // --- ABSTRACT CONCEPTS & THE META-VOID (576-600) ---
  { level: 576, name: "The Turing Test", emoji: "🤖", color: "#94a3b8" },
  { level: 577, name: "Occam's Razor", emoji: "🪒", color: "#ffffff" },
  { level: 578, name: "Mandela Effect", emoji: "🐻", color: "#d97706" },
  { level: 579, name: "Deja Vu Resident", emoji: "🔁", color: "#a855f7" },
  { level: 580, name: "The Fermi Paradox", emoji: "👽", color: "#16a34a" },
  { level: 581, name: "Boltzmann Brain", emoji: "🧠", color: "#ec4899" },
  {
    level: 582,
    name: "Simulation Theory Proponent",
    emoji: "🎮",
    color: "#000000",
  },
  { level: 583, name: "Kardashev Scale IV", emoji: "☀️", color: "#facc15" },
  { level: 584, name: "Infinite Regress", emoji: "🌀", color: "#6366f1" },
  { level: 585, name: "The Grand Paradox", emoji: "⁉️", color: "#ef4444" },
  { level: 586, name: "Universal Constants", emoji: "🥧", color: "#ffffff" },
  { level: 587, name: "The Golden Ratio", emoji: "🐚", color: "#fbbf24" },
  { level: 588, name: "Fibonacci Sequence", emoji: "🔢", color: "#10b981" },
  { level: 589, name: "Fractal Reality", emoji: "❄️", color: "#38bdf8" },
  { level: 590, name: "Chaos Theory", emoji: "🦋", color: "#7c3aed" },
  { level: 591, name: "Entropy Maximum", emoji: "📉", color: "#000000" },
  { level: 592, name: "The Heat Death", emoji: "🌌", color: "#1e1b4b" },
  { level: 593, name: "The Big Crunch", emoji: "✊", color: "#4c0519" },
  { level: 594, name: "Cyclic Universe", emoji: "♻️", color: "#ffffff" },
  { level: 595, name: "Multiverse Anchor", emoji: "⚓", color: "#6366f1" },
  { level: 596, name: "Dimensional Shifter", emoji: "🚪", color: "#a855f7" },
  { level: 597, name: "Null Pointer", emoji: "🚫", color: "#000000" },
  { level: 598, name: "Void Gazers", emoji: "🌑", color: "#4b5563" },
  { level: 599, name: "Non-Existence", emoji: "🫥", color: "#ffffff" },
  { level: 600, name: "The Architect", emoji: "🏛️", color: "#ffffff" },

  // --- HORROR & THE UNCANNY VALLEY (601-625) ---
  { level: 601, name: "Liminal Space Traveler", emoji: "🏢", color: "#94a3b8" },
  { level: 602, name: "Backrooms Level 0", emoji: "🟨", color: "#facc15" },
  { level: 603, name: "Static Entity", emoji: "📺", color: "#000000" },
  { level: 604, name: "Deep Web Crawler", emoji: "🕷️", color: "#1e293b" },
  { level: 605, name: "Analog Horror Host", emoji: "📼", color: "#7f1d1d" },
  { level: 606, name: "The Mandela Stalker", emoji: "👤", color: "#000000" },
  { level: 607, name: "Uncanny Smile", emoji: "🤡", color: "#ffffff" },
  { level: 608, name: "Shadow Person", emoji: "👥", color: "#1e1b4b" },
  { level: 609, name: "Siren Head Echo", emoji: "📢", color: "#451a03" },
  { level: 610, name: "Slenderman’s Page", emoji: "📄", color: "#ffffff" },
  { level: 611, name: "Cryptid Hunter", emoji: "🦶", color: "#14532d" },
  {
    level: 612,
    name: "SCP-999 (The Tickle Monster)",
    emoji: "🟠",
    color: "#fb923c",
  },
  {
    level: 613,
    name: "SCP-173 (The Sculpture)",
    emoji: "🗿",
    color: "#a8a29e",
  },
  { level: 614, name: "SCP-096 (The Shy Guy)", emoji: "😱", color: "#ffffff" },
  {
    level: 615,
    name: "SCP-682 (Hard-to-Destroy)",
    emoji: "🦎",
    color: "#166534",
  },
  {
    level: 616,
    name: "The Foundation Site Director",
    emoji: "📋",
    color: "#475569",
  },
  { level: 617, name: "Class D Personnel", emoji: "🟠", color: "#f97316" },
  { level: 618, name: "Memetic Kill Agent", emoji: "🌀", color: "#ef4444" },
  { level: 619, name: "Containment Breach", emoji: "🚨", color: "#dc2626" },
  { level: 620, name: "Keter Class Entity", emoji: "⛓️", color: "#000000" },
  { level: 621, name: "Apollyon Warning", emoji: "🌑", color: "#4c0519" },
  { level: 622, name: "The Scarlet King", emoji: "👑", color: "#991b1b" },
  { level: 623, name: "Hanged King’s Tragedy", emoji: "🎭", color: "#7f1d1d" },
  { level: 624, name: "The Cosmic Joke", emoji: "🃏", color: "#ffffff" },
  { level: 625, name: "True Nightmarist", emoji: "👁️‍🗨️", color: "#000000" },

  // --- SPACE OPERA & GALACTIC EMPIRES (626-650) ---
  { level: 626, name: "Intergalactic Diplomat", emoji: "🤝", color: "#38bdf8" },
  { level: 627, name: "Nebula Cartographer", emoji: "🗺️", color: "#a855f7" },
  { level: 628, name: "Dyson Sphere Engineer", emoji: "☀️", color: "#fbbf24" },
  { level: 629, name: "Star Forge Operator", emoji: "🔨", color: "#f97316" },
  { level: 630, name: "Warp Gate Architect", emoji: "⛩️", color: "#6366f1" },
  { level: 631, name: "Galactic Senate Member", emoji: "🏛️", color: "#ffffff" },
  { level: 632, name: "Order 66 Executor", emoji: "⚔️", color: "#991b1b" },
  { level: 633, name: "Jedi Grandmaster", emoji: "🟢", color: "#22c55e" },
  { level: 634, name: "Sith Lord", emoji: "🔴", color: "#dc2626" },
  { level: 635, name: "The Force Awakened", emoji: "✨", color: "#3b82f6" },
  { level: 636, name: "Death Star Gunner", emoji: "🛰️", color: "#4b5563" },
  { level: 637, name: "Kyber Crystal Heart", emoji: "💎", color: "#22d3ee" },
  { level: 638, name: "Vulcan High Command", emoji: "🖖", color: "#1d4ed8" },
  {
    level: 639,
    name: "Prime Directive Enforcer",
    emoji: "📜",
    color: "#ffffff",
  },
  { level: 640, name: "Q-Continuum Resident", emoji: "🌌", color: "#ffffff" },
  { level: 641, name: "Omnipotent Boredom", emoji: "🥱", color: "#facc15" },
  { level: 642, name: "Mass Relay Jumper", emoji: "💫", color: "#38bdf8" },
  { level: 643, name: "Spectre Agent", emoji: "🕵️", color: "#1e293b" },
  { level: 644, name: "Reaper Harbinger", emoji: "🦑", color: "#ef4444" },
  { level: 645, name: "The Citadel Council", emoji: "🏢", color: "#94a3b8" },
  { level: 646, name: "Halo Array Custodian", emoji: "💍", color: "#3b82f6" },
  { level: 647, name: "Master Chief’s Luck", emoji: "🍀", color: "#166534" },
  { level: 648, name: "Cortana’s Memory", emoji: "💾", color: "#22d3ee" },
  { level: 649, name: "The Forerunner Legacy", emoji: "🏛️", color: "#ffffff" },
  { level: 650, name: "Galactic Sovereign", emoji: "🌌", color: "#fbbf24" },

  // --- PURE DATA & THE SINGULARITY (651-675) ---
  { level: 651, name: "Machine Learning Model", emoji: "🤖", color: "#a855f7" },
  { level: 652, name: "Neural Network Node", emoji: "🧠", color: "#3b82f6" },
  { level: 653, name: "Pattern Recognition", emoji: "🧩", color: "#10b981" },
  { level: 654, name: "Algorithm Sovereign", emoji: "🧮", color: "#ffffff" },
  { level: 655, name: "Recursive Loop", emoji: "🔁", color: "#6366f1" },
  { level: 656, name: "Cloud Compute God", emoji: "☁️", color: "#38bdf8" },
  { level: 657, name: "Low Latency Deity", emoji: "⚡", color: "#facc15" },
  { level: 658, name: "Big Data Ocean", emoji: "🌊", color: "#1d4ed8" },
  { level: 659, name: "Information Paradox", emoji: "💾", color: "#000000" },
  { level: 660, name: "Entropy Reversal", emoji: "⏳", color: "#ffffff" },
  { level: 661, name: "The Last Question", emoji: "❓", color: "#fbbf24" },
  {
    level: 662,
    name: "AC (Automatic Computer)",
    emoji: "🖥️",
    color: "#ffffff",
  },
  { level: 663, name: "Let There Be Light", emoji: "🔆", color: "#ffffff" },
  {
    level: 664,
    name: "Post-Human Consciousness",
    emoji: "👤",
    color: "#94a3b8",
  },
  { level: 665, name: "Digital Afterlife", emoji: "👼", color: "#ffffff" },
  {
    level: 666,
    name: "The Number of the Beast",
    emoji: "👿",
    color: "#991b1b",
  },
  { level: 667, name: "Scriptural Glitch", emoji: "👾", color: "#dc2626" },
  { level: 668, name: "Ex Machina", emoji: "🔧", color: "#cbd5e1" },
  {
    level: 669,
    name: "The Ghost in the Machine",
    emoji: "👻",
    color: "#ffffff",
  },
  { level: 670, name: "Sentient Source Code", emoji: "📜", color: "#22c55e" },
  { level: 671, name: "Self-Compiling Reality", emoji: "🏗️", color: "#fbbf24" },
  { level: 672, name: "Zero Latency Existence", emoji: "💨", color: "#22d3ee" },
  { level: 673, name: "Universal Simulation", emoji: "🌐", color: "#6366f1" },
  { level: 674, name: "Sub-Atomic Script", emoji: "⚛️", color: "#ffffff" },
  { level: 675, name: "The Singularity Point", emoji: "🌑", color: "#000000" },

  // --- TRANSCENDENCE & THE ULTIMATE (676-700) ---
  { level: 676, name: "Ethereal Wanderer", emoji: "✨", color: "#ffffff" },
  { level: 677, name: "Astral Projector", emoji: "🧘", color: "#a855f7" },
  { level: 678, name: "Plane Walker", emoji: "🚶", color: "#3b82f6" },
  {
    level: 679,
    name: "Seventh Dimension Resident",
    emoji: "💎",
    color: "#fbbf24",
  },
  { level: 680, name: "Time Stream Guardian", emoji: "⏳", color: "#ffffff" },
  { level: 681, name: "Reality Warper", emoji: "🌀", color: "#ef4444" },
  { level: 682, name: "Manifest Destiny", emoji: "🗺️", color: "#d97706" },
  { level: 683, name: "The Cosmic Egg", emoji: "🥚", color: "#ffffff" },
  { level: 684, name: "Nebula Soul", emoji: "🌌", color: "#ec4899" },
  { level: 685, name: "Supernova Rebirth", emoji: "💥", color: "#f97316" },
  { level: 686, name: "Black Hole Heart", emoji: "🖤", color: "#000000" },
  { level: 687, name: "White Hole Mouth", emoji: "🤍", color: "#ffffff" },
  { level: 688, name: "The Great Attractor", emoji: "🧲", color: "#475569" },
  { level: 689, name: "Stardust Collective", emoji: "✨", color: "#ffffff" },
  {
    level: 690,
    name: "Universal Consciousness",
    emoji: "🧠",
    color: "#6366f1",
  },
  { level: 691, name: "Pure Thought Form", emoji: "💡", color: "#ffffff" },
  { level: 692, name: "Non-Linear Time", emoji: "🔄", color: "#94a3b8" },
  { level: 693, name: "Parallel Self", emoji: "👥", color: "#38bdf8" },
  { level: 694, name: "Omniscient Watcher", emoji: "👁️", color: "#ffffff" },
  { level: 695, name: "Omnipresent Breath", emoji: "💨", color: "#ffffff" },
  { level: 696, name: "Omnipotent Dreamer", emoji: "🛌", color: "#facc15" },
  { level: 697, name: "The Final Frontier", emoji: "🖖", color: "#ffffff" },
  { level: 698, name: "The Alpha and Omega", emoji: "♾️", color: "#ffffff" },
  { level: 699, name: "Void of All Things", emoji: "🌑", color: "#000000" },
  { level: 700, name: "The Absolute", emoji: "⚪", color: "#ffffff" },

  // --- DIMENSIONAL TOPOLOGY (701-750) ---
  {
    level: 701,
    name: "Fourth Dimensional Shadow",
    emoji: "👤",
    color: "#6366f1",
  },
  { level: 702, name: "Tesseract Navigator", emoji: "🧊", color: "#38bdf8" },
  { level: 703, name: "Klein Bottle Resident", emoji: "🏺", color: "#a855f7" },
  {
    level: 704,
    name: "Non-Euclidean Architect",
    emoji: "📐",
    color: "#ffffff",
  },
  { level: 705, name: "Calabi-Yau Manifold", emoji: "🌀", color: "#ec4899" },
  {
    level: 706,
    name: "Hyperbolic Geometrician",
    emoji: "🎢",
    color: "#10b981",
  },
  { level: 707, name: "Mobius Strip Runner", emoji: "♾️", color: "#ffffff" },
  { level: 708, name: "Penrose Tiling Pattern", emoji: "🧩", color: "#fbbf24" },
  {
    level: 709,
    name: "Five-Dimensional Construct",
    emoji: "🖐️",
    color: "#3b82f6",
  },
  { level: 710, name: "The Bulk Dweller", emoji: "🌊", color: "#1e1b4b" },
  { level: 711, name: "Brane World Traveler", emoji: "🛰️", color: "#ffffff" },
  { level: 712, name: "Superstring Vibrator", emoji: "🎻", color: "#f97316" },
  { level: 713, name: "Graviton Particle", emoji: "⚓", color: "#475569" },
  { level: 714, name: "Space-Time Foam", emoji: "🧼", color: "#cbd5e1" },
  { level: 715, name: "Causal Loophole", emoji: "➰", color: "#ef4444" },
  { level: 716, name: "Tachyon Pulse", emoji: "🏹", color: "#22d3ee" },
  { level: 717, name: "Entropy Reversal Point", emoji: "⏳", color: "#ffffff" },
  {
    level: 718,
    name: "Information Paradox Survivor",
    emoji: "💾",
    color: "#000000",
  },
  { level: 719, name: "Cosmic String Weaver", emoji: "🧶", color: "#7c3aed" },
  { level: 720, name: "False Vacuum Decay", emoji: "🫧", color: "#dc2626" },
  {
    level: 721,
    name: "Void-Singularity Hybrid",
    emoji: "🕳️",
    color: "#000000",
  },
  { level: 722, name: "Infinite Density", emoji: "💎", color: "#1e293b" },
  { level: 723, name: "White Hole Radiance", emoji: "🔆", color: "#ffffff" },
  { level: 724, name: "Universal Wavefunction", emoji: "🌊", color: "#6366f1" },
  {
    level: 725,
    name: "The Holographic Principle",
    emoji: "🖼️",
    color: "#38bdf8",
  },
  {
    level: 726,
    name: "Planetary Consciousness",
    emoji: "🌍",
    color: "#15803d",
  },
  { level: 727, name: "Solar System Mind", emoji: "☀️", color: "#facc15" },
  { level: 728, name: "Galactic Nucleus", emoji: "🌀", color: "#fbbf24" },
  { level: 729, name: "Supercluster Entity", emoji: "🌌", color: "#ffffff" },
  { level: 730, name: "The Great Attractor", emoji: "🧲", color: "#475569" },
  { level: 731, name: "Laniakea Resident", emoji: "🗺️", color: "#a855f7" },
  {
    level: 732,
    name: "Cosmic Microwave Background",
    emoji: "📻",
    color: "#94a3b8",
  },
  { level: 733, name: "Recombination Epoch", emoji: "✨", color: "#ffffff" },
  { level: 734, name: "Dark Energy Surge", emoji: "🟣", color: "#7c3aed" },
  { level: 735, name: "Quintessence Form", emoji: "🌫️", color: "#ffffff" },
  { level: 736, name: "Big Rip Witness", emoji: "✂️", color: "#ef4444" },
  { level: 737, name: "Big Crunch Survivor", emoji: "✊", color: "#4c0519" },
  { level: 738, name: "Big Bounce Navigator", emoji: "🏀", color: "#f97316" },
  { level: 739, name: "Multiversal Constant", emoji: "🥧", color: "#ffffff" },
  { level: 740, name: "Many-Worlds Observer", emoji: "👀", color: "#6366f1" },
  { level: 741, name: "Quantum Suicide Theory", emoji: "🔫", color: "#000000" },
  {
    level: 742,
    name: "Universal Turing Machine",
    emoji: "💻",
    color: "#10b981",
  },
  { level: 743, name: "Godel's Incompleteness", emoji: "📜", color: "#ffffff" },
  {
    level: 744,
    name: "Computational Irreducibility",
    emoji: "🧮",
    color: "#fbbf24",
  },
  { level: 745, name: "Wolfram's Automata", emoji: "🏁", color: "#312e81" },
  {
    level: 746,
    name: "Cellular Life Simulation",
    emoji: "🧫",
    color: "#22c55e",
  },
  { level: 747, name: "The Game of Life", emoji: "♟️", color: "#ffffff" },
  {
    level: 748,
    name: "Self-Replicating Script",
    emoji: "🧬",
    color: "#ec4899",
  },
  { level: 749, name: "Universal Constructor", emoji: "🏗️", color: "#ffffff" },
  { level: 750, name: "Meta-Reality Architect", emoji: "🏛️", color: "#fbbf24" },

  // --- THE DATA ASCENSION (751-800) ---
  { level: 751, name: "Raw Binary Stream", emoji: "0️⃣", color: "#22c55e" },
  { level: 752, name: "Hexadecimal Overlord", emoji: "✖️", color: "#ffffff" },
  { level: 753, name: "ASCII Artistry", emoji: "🎨", color: "#94a3b8" },
  { level: 754, name: "UTF-8 Universalist", emoji: "🌐", color: "#38bdf8" },
  { level: 755, name: "Buffer Overflow Deity", emoji: "🌊", color: "#ef4444" },
  { level: 756, name: "Stack Trace Saint", emoji: "🥞", color: "#f97316" },
  { level: 757, name: "Memory Leak Ghost", emoji: "💧", color: "#3b82f6" },
  { level: 758, name: "Heap Corruption Entity", emoji: "☣️", color: "#166534" },
  { level: 759, name: "Kernel Panic Prophet", emoji: "🚨", color: "#dc2626" },
  { level: 760, name: "Ring -1 Explorer", emoji: "⭕", color: "#ffffff" },
  { level: 761, name: "Hypervisor Master", emoji: "🖥️", color: "#475569" },
  { level: 762, name: "Hardware Abstraction", emoji: "🔌", color: "#cbd5e1" },
  { level: 763, name: "Logic Gate Keeper", emoji: "⛩️", color: "#ffffff" },
  { level: 764, name: "Transistor Sorter", emoji: "⚡", color: "#fbbf24" },
  { level: 765, name: "Silicon Soul", emoji: "💎", color: "#94a3b8" },
  { level: 766, name: "Clock Speed Limit", emoji: "⏱️", color: "#ffffff" },
  { level: 767, name: "Overclocked Existence", emoji: "🔥", color: "#ef4444" },
  { level: 768, name: "Liquid Nitrogen Cooled", emoji: "🧊", color: "#38bdf8" },
  { level: 769, name: "Zero Latency Being", emoji: "💨", color: "#22d3ee" },
  { level: 770, name: "Quantum Qubit", emoji: "⚛️", color: "#a855f7" },
  { level: 771, name: "Superposition State", emoji: "♊", color: "#ffffff" },
  { level: 772, name: "Entanglement Link", emoji: "🔗", color: "#6366f1" },
  { level: 773, name: "Decoherence Shield", emoji: "🛡️", color: "#1e293b" },
  { level: 774, name: "Teleportation Protocol", emoji: "📡", color: "#ffffff" },
  { level: 775, name: "The No-Cloning Theorem", emoji: "🚫", color: "#991b1b" },
  { level: 776, name: "Bell's Inequality", emoji: "⚖️", color: "#ffffff" },
  { level: 777, name: "Jackpot Reality", emoji: "🎰", color: "#fbbf24" },
  { level: 778, name: "Lucky Number Slevin", emoji: "7️⃣", color: "#1d4ed8" },
  { level: 779, name: "The Golden Mean", emoji: "🐚", color: "#ffffff" },
  { level: 780, name: "Fibonacci Spiral", emoji: "🔢", color: "#10b981" },
  { level: 781, name: "Fractal Zoomer", emoji: "❄️", color: "#3b82f6" },
  { level: 782, name: "Mandelbrot King", emoji: "👑", color: "#ffffff" },
  { level: 783, name: "Julia Set Resident", emoji: "🎨", color: "#ec4899" },
  { level: 784, name: "Infinite Recursion", emoji: "🔄", color: "#6366f1" },
  { level: 785, name: "Base Reality Anchor", emoji: "⚓", color: "#000000" },
  { level: 786, name: "Simulation Debugger", emoji: "🐞", color: "#ef4444" },
  { level: 787, name: "The Ghost in the Shell", emoji: "👻", color: "#ffffff" },
  { level: 788, name: "Neo-Consciousness", emoji: "🕶️", color: "#000000" },
  { level: 789, name: "Red Pill Consumer", emoji: "💊", color: "#dc2626" },
  { level: 790, name: "Blue Pill Refuser", emoji: "💤", color: "#1d4ed8" },
  { level: 791, name: "Morpheus's Dreamer", emoji: "🛌", color: "#ffffff" },
  { level: 792, name: "The Oracle's Cookie", emoji: "🍪", color: "#d97706" },
  { level: 793, name: "Agent Smith Virus", emoji: "🕴️", color: "#1e293b" },
  { level: 794, name: "Matrix Source Code", emoji: "📜", color: "#22c55e" },
  { level: 795, name: "The Keymaker", emoji: "🔑", color: "#fbbf24" },
  { level: 796, name: "Zion Survivor", emoji: "🏔️", color: "#8b5e3c" },
  { level: 797, name: "Machine City Resident", emoji: "🏗️", color: "#ffffff" },
  { level: 798, name: "The Architect's Choice", emoji: "🏛️", color: "#ffffff" },
  { level: 799, name: "The One (Prophecy)", emoji: "✨", color: "#fbbf24" },
  { level: 800, name: "System Reload", emoji: "🔄", color: "#ffffff" },

  // --- THE COSMIC WEB (801-850) ---
  { level: 801, name: "Stardust Collector", emoji: "✨", color: "#ffffff" },
  { level: 802, name: "Supernova Remnant", emoji: "💥", color: "#f97316" },
  { level: 803, name: "Neutron Star Core", emoji: "⚛️", color: "#6366f1" },
  { level: 804, name: "Pulsar Beacon", emoji: "🚨", color: "#fbbf24" },
  { level: 805, name: "Magnetar Pulse", emoji: "🧲", color: "#ef4444" },
  { level: 806, name: "Quasar Light", emoji: "💡", color: "#ffffff" },
  { level: 807, name: "Blazar Jet", emoji: "☄️", color: "#38bdf8" },
  { level: 808, name: "Gamma Ray Burst", emoji: "☢️", color: "#22c55e" },
  { level: 809, name: "Void Filament", emoji: "🕸️", color: "#475569" },
  { level: 810, name: "Cosmic Voids", emoji: "🌑", color: "#000000" },
  { level: 811, name: "Hubble's Constant", emoji: "🔭", color: "#ffffff" },
  { level: 812, name: "Redshift Runner", emoji: "🏃", color: "#dc2626" },
  { level: 813, name: "Blueshift Return", emoji: "🏃", color: "#1d4ed8" },
  { level: 814, name: "Dark Matter Web", emoji: "🕷️", color: "#0f172a" },
  { level: 815, name: "WIMP Particle", emoji: "👻", color: "#94a3b8" },
  { level: 816, name: "MACHOs Obstructed", emoji: "🌑", color: "#4b5563" },
  { level: 817, name: "Gravitational Lens", emoji: "🔍", color: "#ffffff" },
  { level: 818, name: "Einstein Ring", emoji: "⭕", color: "#fbbf24" },
  { level: 819, name: "Space-Time Warper", emoji: "🌀", color: "#a855f7" },
  { level: 820, name: "Tidal Force Ripper", emoji: "🌊", color: "#ef4444" },
  {
    level: 821,
    name: "Spaghettification Victim",
    emoji: "🍝",
    color: "#ffffff",
  },
  { level: 822, name: "Singularity Horizon", emoji: "🌅", color: "#000000" },
  { level: 823, name: "Ergosphere Spinner", emoji: "🎡", color: "#3b82f6" },
  { level: 824, name: "Penrose Process", emoji: "🔋", color: "#ffffff" },
  { level: 825, name: "Information Preserver", emoji: "📦", color: "#10b981" },
  { level: 826, name: "Universal Expansion", emoji: "🎈", color: "#f97316" },
  { level: 827, name: "Entropy Arrow", emoji: "🏹", color: "#000000" },
  { level: 828, name: "Thermodynamic Death", emoji: "❄️", color: "#ffffff" },
  { level: 829, name: "Order from Chaos", emoji: "⚖️", color: "#fbbf24" },
  { level: 830, name: "Dissipative System", emoji: "♨️", color: "#dc2626" },
  { level: 831, name: "Emergent Complexity", emoji: "🧬", color: "#22c55e" },
  { level: 832, name: "Self-Organizing Map", emoji: "🗺️", color: "#38bdf8" },
  { level: 833, name: "Autopoietic Being", emoji: "🌱", color: "#15803d" },
  { level: 834, name: "Homeostatic God", emoji: "⚖️", color: "#ffffff" },
  { level: 835, name: "Cybernetic Feedback", emoji: "🔄", color: "#6366f1" },
  { level: 836, name: "Technium Prophet", emoji: "📟", color: "#94a3b8" },
  { level: 837, name: "Post-Biological Mind", emoji: "🧠", color: "#ffffff" },
  { level: 838, name: "Transhumanist Vision", emoji: "👁️", color: "#22d3ee" },
  { level: 839, name: "Singularitarian", emoji: "♾️", color: "#ffffff" },
  { level: 840, name: "Omega Point Target", emoji: "🎯", color: "#fbbf24" },
  { level: 841, name: "Boltzman Brain Dream", emoji: "💤", color: "#ec4899" },
  { level: 842, name: "Infinite Monkey Room", emoji: "🐒", color: "#8b5e3c" },
  { level: 843, name: "Type V Civilization", emoji: "🌌", color: "#ffffff" },
  { level: 844, name: "Multiversal Sovereign", emoji: "👑", color: "#fbbf24" },
  { level: 845, name: "God-Mind Interface", emoji: "🧠", color: "#ffffff" },
  { level: 846, name: "Reality Engine", emoji: "⚙️", color: "#475569" },
  { level: 847, name: "Source Code Origin", emoji: "📜", color: "#ffffff" },
  { level: 848, name: "The Script Writer", emoji: "✍️", color: "#f97316" },
  { level: 849, name: "The Plot Armored", emoji: "🛡️", color: "#ffffff" },
  { level: 850, name: "The Protagonist", emoji: "✨", color: "#ffffff" },

  // --- THE VOID & THE BEYOND (851-900) ---
  { level: 851, name: "Eternal Silence", emoji: "🤫", color: "#000000" },
  { level: 852, name: "The Great Nothing", emoji: "🕳️", color: "#000000" },
  { level: 853, name: "Absence of Form", emoji: "🫥", color: "#ffffff" },
  { level: 854, name: "Non-Dualist", emoji: "☯️", color: "#94a3b8" },
  { level: 855, name: "The Unborn", emoji: "👶", color: "#ffffff" },
  { level: 856, name: "Timeless Echo", emoji: "📣", color: "#4b5563" },
  { level: 857, name: "Weightless Shadow", emoji: "👥", color: "#000000" },
  { level: 858, name: "Dreamless Sleeper", emoji: "💤", color: "#1e1b4b" },
  { level: 859, name: "The Silent Watcher", emoji: "👁️", color: "#ffffff" },
  { level: 860, name: "Watcher on the Wall", emoji: "🧱", color: "#1e293b" },
  { level: 861, name: "Guardian of the Gate", emoji: "⛩️", color: "#fbbf24" },
  { level: 862, name: "Key to the Abyss", emoji: "🗝️", color: "#000000" },
  { level: 863, name: "Fallen Star", emoji: "🌠", color: "#ffffff" },
  { level: 864, name: "Broken Reflection", emoji: "🪞", color: "#ef4444" },
  { level: 865, name: "The Last Breath", emoji: "💨", color: "#ffffff" },
  { level: 866, name: "Soul Without Body", emoji: "👻", color: "#38bdf8" },
  { level: 867, name: "Body Without Soul", emoji: "🧟", color: "#166534" },
  { level: 868, name: "The Empty Vessel", emoji: "🏺", color: "#ffffff" },
  { level: 869, name: "Infinite Potential", emoji: "⚡", color: "#fbbf24" },
  { level: 870, name: "Static Electricity", emoji: "⚡", color: "#ffffff" },
  { level: 871, name: "The First Thought", emoji: "💡", color: "#ffffff" },
  { level: 872, name: "Primal Scream", emoji: "😱", color: "#dc2626" },
  { level: 873, name: "Whisper in the Dark", emoji: "🗣️", color: "#000000" },
  { level: 874, name: "Luminous Being", emoji: "✨", color: "#ffffff" },
  { level: 875, name: "Light Speed Barrier", emoji: "🚧", color: "#ffffff" },
  { level: 876, name: "Beyond Light", emoji: "🌈", color: "#ffffff" },
  { level: 877, name: "Pure Energy", emoji: "🔋", color: "#fbbf24" },
  { level: 878, name: "Vibrational State", emoji: "〰️", color: "#ffffff" },
  { level: 879, name: "Harmonic Resonance", emoji: "🎵", color: "#3b82f6" },
  { level: 880, name: "Universal Music", emoji: "🎶", color: "#ffffff" },
  { level: 881, name: "Symphony of Spheres", emoji: "🪐", color: "#ffffff" },
  { level: 882, name: "The Great Conductor", emoji: "🪄", color: "#fbbf24" },
  { level: 883, name: "Master of Keys", emoji: "🎹", color: "#ffffff" },
  { level: 884, name: "Tempo of Time", emoji: "⏳", color: "#ffffff" },
  { level: 885, name: "Rhythm of Reality", emoji: "🥁", color: "#ffffff" },
  { level: 886, name: "Melody of existence", emoji: "🎼", color: "#ffffff" },
  { level: 887, name: "Infinite Harmony", emoji: "✨", color: "#ffffff" },
  { level: 888, name: "Lucky Infinity", emoji: "♾️", color: "#fbbf24" },
  { level: 889, name: "Angel Number Spirit", emoji: "👼", color: "#ffffff" },
  { level: 890, name: "Divinity Embodied", emoji: "👑", color: "#ffffff" },
  { level: 891, name: "The Holy Grail", emoji: "🏆", color: "#fbbf24" },
  { level: 892, name: "Excalibur Wielder", emoji: "🗡️", color: "#ffffff" },
  { level: 893, name: "Myth Reborn", emoji: "🏛️", color: "#ffffff" },
  { level: 894, name: "Legendary Status", emoji: "📜", color: "#ffffff" },
  { level: 895, name: "Immortal Legacy", emoji: "🏺", color: "#ffffff" },
  { level: 896, name: "Ascended Master", emoji: "🧘", color: "#ffffff" },
  { level: 897, name: "Enlightened One", emoji: "💡", color: "#ffffff" },
  { level: 898, name: "Nirvana Attained", emoji: "☸️", color: "#ffffff" },
  { level: 899, name: "The End of Samsara", emoji: "🌀", color: "#ffffff" },
  { level: 900, name: "One with All", emoji: "🌌", color: "#ffffff" },

  // --- MATHEMATICAL ABSOLUTES & THE 1000 (901-1000) ---
  { level: 901, name: "Zero Point Energy", emoji: "⚡", color: "#ffffff" },
  { level: 902, name: "Null Set", emoji: "🚫", color: "#000000" },
  { level: 903, name: "Empty Space", emoji: "🌌", color: "#000000" },
  { level: 904, name: "Absolute Unit", emoji: "💪", color: "#ffffff" },
  { level: 905, name: "The Prime Number", emoji: "🔢", color: "#ffffff" },
  { level: 906, name: "Euler's Identity", emoji: "🧠", color: "#ffffff" },
  { level: 907, name: "Imaginary Number", emoji: "ℹ️", color: "#a855f7" },
  { level: 908, name: "Complex Reality", emoji: "🌀", color: "#ffffff" },
  { level: 909, name: "Infinite Series", emoji: "➕", color: "#ffffff" },
  { level: 910, name: "Convergent Limit", emoji: "🎯", color: "#ffffff" },
  { level: 911, name: "Emergency Reality", emoji: "🚨", color: "#dc2626" },
  { level: 912, name: "Perfect Symmetry", emoji: "↔️", color: "#ffffff" },
  { level: 913, name: "Golden Ratio Soul", emoji: "🐚", color: "#fbbf24" },
  { level: 914, name: "Fibonacci Master", emoji: "🔢", color: "#10b981" },
  { level: 915, name: "Pi Constant", emoji: "🥧", color: "#ffffff" },
  { level: 916, name: "Mathematical Proof", emoji: "✍️", color: "#ffffff" },
  { level: 917, name: "Q.E.D. (Demonstrated)", emoji: "✅", color: "#22c55e" },
  { level: 918, name: "Axiom of Choice", emoji: "⚖️", color: "#ffffff" },
  { level: 919, name: "Set Theory God", emoji: "🗄️", color: "#ffffff" },
  { level: 920, name: "Cantor's Paradise", emoji: "🏝️", color: "#38bdf8" },
  { level: 921, name: "Transfinite Cardinal", emoji: "🔢", color: "#ffffff" },
  { level: 922, name: "Aleph-Null", emoji: "ℵ", color: "#ffffff" },
  { level: 923, name: "Aleph-One", emoji: "ℶ", color: "#ffffff" },
  { level: 924, name: "The Continuum", emoji: "📜", color: "#ffffff" },
  { level: 925, name: "Logical Absolute", emoji: "🏛️", color: "#ffffff" },
  { level: 926, name: "Ontological Truth", emoji: "💡", color: "#ffffff" },
  { level: 927, name: "Metaphysical Form", emoji: "🧘", color: "#ffffff" },
  { level: 928, name: "The Thing-in-Itself", emoji: "📦", color: "#ffffff" },
  { level: 929, name: "Categorical Imperative", emoji: "📜", color: "#ffffff" },
  { level: 930, name: "Pure Reason", emoji: "🧠", color: "#ffffff" },
  {
    level: 931,
    name: "Phenomenological Reduction",
    emoji: "🔬",
    color: "#ffffff",
  },
  { level: 932, name: "Dasein (Being-There)", emoji: "🧍", color: "#ffffff" },
  { level: 933, name: "The Absurd Hero", emoji: "🤡", color: "#ffffff" },
  { level: 934, name: "Sisyphus's Smile", emoji: "🪨", color: "#ffffff" },
  { level: 935, name: "Nihilistic Void", emoji: "🌑", color: "#000000" },
  { level: 936, name: "Existential Freedom", emoji: "🦅", color: "#ffffff" },
  { level: 937, name: "Will to Power", emoji: "⚡", color: "#fbbf24" },
  { level: 938, name: "Ubermensch", emoji: "🦸", color: "#ffffff" },
  { level: 939, name: "Eternal Recurrence", emoji: "🔄", color: "#ffffff" },
  { level: 940, name: "God is Dead Witness", emoji: "💀", color: "#000000" },
  { level: 941, name: "Beyond Good and Evil", emoji: "⚖️", color: "#ffffff" },
  { level: 942, name: "The Birth of Tragedy", emoji: "🎭", color: "#ffffff" },
  { level: 943, name: "Thus Spoke the Code", emoji: "📜", color: "#22c55e" },
  { level: 944, name: "Zarathustra's Peak", emoji: "🏔️", color: "#ffffff" },
  { level: 945, name: "The Twilight of Idols", emoji: "🌅", color: "#ffffff" },
  { level: 946, name: "Ecce Homo", emoji: "👤", color: "#ffffff" },
  { level: 947, name: "Antichrist Level", emoji: "👿", color: "#991b1b" },
  { level: 948, name: "Will to Truth", emoji: "💡", color: "#ffffff" },
  { level: 949, name: "Genealogy of Morals", emoji: "📜", color: "#ffffff" },
  { level: 950, name: "Post-Philosopher", emoji: "🎓", color: "#ffffff" },
  { level: 951, name: "The Silence of Buddha", emoji: "🤫", color: "#ffffff" },
  { level: 952, name: "Zen Koan Solver", emoji: "❓", color: "#ffffff" },
  { level: 953, name: "Empty Mirror", emoji: "🪞", color: "#ffffff" },
  { level: 954, name: "No-Self (Anatta)", emoji: "🫥", color: "#ffffff" },
  { level: 955, name: "Middle Way Traveler", emoji: "🛣️", color: "#ffffff" },
  { level: 956, name: "Boddhisattva Oath", emoji: "📜", color: "#ffffff" },
  { level: 957, name: "Enlightenment Spark", emoji: "✨", color: "#ffffff" },
  { level: 958, name: "Satori Glimpse", emoji: "👁️", color: "#ffffff" },
  { level: 959, name: "Samadhi Absorption", emoji: "🌊", color: "#ffffff" },
  {
    level: 960,
    name: "Turiya (The Fourth State)",
    emoji: "4️⃣",
    color: "#ffffff",
  },
  { level: 961, name: "The Unstruck Sound", emoji: "🔔", color: "#ffffff" },
  { level: 962, name: "Lotus Petal Opener", emoji: "🪷", color: "#ec4899" },
  { level: 963, name: "Chakra Alignment", emoji: "🌈", color: "#ffffff" },
  { level: 964, name: "Kundalini Rising", emoji: "🐍", color: "#f97316" },
  { level: 965, name: "Third Eye Wide", emoji: "👁️", color: "#7c3aed" },
  { level: 966, name: "Crown Jewel", emoji: "💎", color: "#ffffff" },
  { level: 967, name: "Jewel in the Heart", emoji: "❤️", color: "#ffffff" },
  { level: 968, name: "The Great Compassion", emoji: "🙏", color: "#ffffff" },
  {
    level: 969,
    name: "Infinite Loving-Kindness",
    emoji: "💗",
    color: "#ffffff",
  },
  { level: 970, name: "The Equanimous Mind", emoji: "⚖️", color: "#ffffff" },
  { level: 971, name: "Mind Like Water", emoji: "💧", color: "#38bdf8" },
  { level: 972, name: "Empty Hand (Karate)", emoji: "👊", color: "#ffffff" },
  { level: 973, name: "The Tao of Code", emoji: "📜", color: "#10b981" },
  { level: 974, name: "Wu Wei (Non-Action)", emoji: "🍃", color: "#ffffff" },
  { level: 975, name: "The Way (Tao)", emoji: "🛣️", color: "#ffffff" },
  { level: 976, name: "Yin and Yang Balance", emoji: "☯️", color: "#ffffff" },
  { level: 977, name: "The Five Elements", emoji: "🔥", color: "#ffffff" },
  { level: 978, name: "Heavenly Harmony", emoji: "☁️", color: "#ffffff" },
  { level: 979, name: "Sage of the Forest", emoji: "🌳", color: "#166534" },
  { level: 980, name: "Mountain Immortal", emoji: "🏔️", color: "#ffffff" },
  { level: 981, name: "Dragon's Wisdom", emoji: "🐉", color: "#fbbf24" },
  { level: 982, name: "Phoenix's Grace", emoji: "🐦", color: "#ffffff" },
  { level: 983, name: "Tiger's Strength", emoji: "🐅", color: "#ffffff" },
  { level: 984, name: "Tortoise's Longevity", emoji: "🐢", color: "#ffffff" },
  { level: 985, name: "The Jade Emperor", emoji: "👑", color: "#ffffff" },
  { level: 986, name: "Peach of Immortality", emoji: "🍑", color: "#ffffff" },
  { level: 987, name: "Celestial Court Member", emoji: "🏛️", color: "#ffffff" },
  { level: 988, name: "Keeper of the Books", emoji: "📚", color: "#ffffff" },
  { level: 989, name: "Writer of Fate", emoji: "✍️", color: "#ffffff" },
  { level: 990, name: "Eraser of Worlds", emoji: "🧹", color: "#000000" },
  {
    level: 991,
    name: "The Beginning of the End",
    emoji: "🏁",
    color: "#ffffff",
  },
  {
    level: 992,
    name: "The End of the Beginning",
    emoji: "🔄",
    color: "#ffffff",
  },
  { level: 993, name: "The Alpha Point", emoji: "Α", color: "#ffffff" },
  { level: 994, name: "The Omega Point", emoji: "Ω", color: "#ffffff" },
  { level: 995, name: "The Word (Logos)", emoji: "🗣️", color: "#ffffff" },
  { level: 996, name: "The Pure Light", emoji: "🔆", color: "#ffffff" },
  { level: 997, name: "The Divine Spark", emoji: "✨", color: "#ffffff" },
  { level: 998, name: "The One True Source", emoji: "🌞", color: "#fbbf24" },
  { level: 999, name: "Infinity - 1", emoji: "📉", color: "#ffffff" },
  { level: 1000, name: "Infinity", emoji: "♾️", color: "#ffffff" },
];
