# https://github.com/j178/prek
name: Manual hooks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  prek-manual:
    name: 🏃‍♂️‍➡️ prek on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run prek-action
        uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2.0.2
        with:
          install-only: true
      - name: Run manual prek hooks
        run: prek run --all-files --hook-stage manual
