# https://github.com/j178/prek
name: 🧹 Prek - Standard Hooks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  prek:
    name: Prek Standard Hooks - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run prek-action
        uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          extra-args: --all-files
