name: Super-Linter

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Run Super-Linter
    runs-on: ubuntu-latest
    permissions:
      # contents permission to clone the repository
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
          persist-credentials: false
      - name: Super-Linter
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_BIOME_LINT: true
          VALIDATE_BIOME_FORMAT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
